ALTER TABLE item_source ADD COLUMN IF NOT EXISTS marketplace_code TEXT;
ALTER TABLE item_source ADD COLUMN IF NOT EXISTS source_item_id TEXT;
ALTER TABLE item_source ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE item_source ADD COLUMN IF NOT EXISTS brand TEXT;
ALTER TABLE item_source ADD COLUMN IF NOT EXISTS condition TEXT;
ALTER TABLE item_source ADD COLUMN IF NOT EXISTS price_cents INTEGER;
ALTER TABLE item_source ADD COLUMN IF NOT EXISTS currency CHAR(3);
ALTER TABLE item_source ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE item_source ADD COLUMN IF NOT EXISTS seller_url TEXT;
ALTER TABLE item_source ADD COLUMN IF NOT EXISTS size TEXT;
ALTER TABLE item_source ADD COLUMN IF NOT EXISTS color TEXT;
ALTER TABLE item_source ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE item_source ADD COLUMN IF NOT EXISTS raw JSONB;
ALTER TABLE item_source ADD COLUMN IF NOT EXISTS first_seen TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE item_source ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
CREATE INDEX IF NOT EXISTS idx_item_source_marketplace ON item_source (marketplace_code);
CREATE INDEX IF NOT EXISTS idx_item_source_brand ON item_source (LOWER(brand));
CREATE INDEX IF NOT EXISTS idx_item_source_updated_at ON item_source (updated_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_item_source_marketplace_source ON item_source (marketplace_code, source_item_id);

ALTER TABLE item_canonical ADD COLUMN IF NOT EXISTS hash_key TEXT;
ALTER TABLE item_canonical ADD COLUMN IF NOT EXISTS brand TEXT;
ALTER TABLE item_canonical ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE item_canonical ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE item_canonical ADD COLUMN IF NOT EXISTS size_norm TEXT;
ALTER TABLE item_canonical ADD COLUMN IF NOT EXISTS color_norm TEXT;
ALTER TABLE item_canonical ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE item_canonical ADD COLUMN IF NOT EXISTS min_price_cents INTEGER;
ALTER TABLE item_canonical ADD COLUMN IF NOT EXISTS currency CHAR(3);
ALTER TABLE item_canonical ADD COLUMN IF NOT EXISTS first_seen TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE item_canonical ADD COLUMN IF NOT EXISTS last_seen TIMESTAMPTZ DEFAULT NOW();
CREATE UNIQUE INDEX IF NOT EXISTS idx_item_canonical_hash ON item_canonical (hash_key);
